### PR TITLE
Merging Otways Branch

### PR DESCRIPTION
**Pull request by osbornejr**
Bringing in the Otways specific scenarios

### CODE REVIEW

**Comment by dhixsingh** [comment]
Your `BlockageTorquay...` test failed @osbornejr. If you could please fix that first. Make sure there is at least some new test for your Otways contribution that does actually run and pass the full checks. 

Could you also point me to the tests you have added.

**Comment by dhixsingh** [comment]
Btw you just have to make the fix on your master and push it to your fork as usual, and this PR will pick that up automatically.

**Comment by osbornejr** [comment]
That's strange, on my fork travis is passing. That particular test was the one giving me the most trouble when I last merged in kaibranch, but it definitely builds on the fork now.

**Comment by osbornejr** [comment]
The four tests I have added are:
Otways300WithTouristsTest
OtwaysBlockage50Test
BlockageTorquay500Test
CongestionTorquay500Test

**Comment by osbornejr** [comment]
The travis config files are the same. Maybe I'll try merge the Denmark kaibranch commit and see if that causes a failure on my end.

**Comment by dhixsingh** [comment]
Pasting the error from the [Travis log](https://api.travis-ci.org/v3/job/351096131/log.txt) below:
```
java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.matsim.withinday.utils.EditTrips.replanCurrentLegWithNetworkRoute(EditTrips.java:131)
	at org.matsim.withinday.utils.EditTrips.replanCurrentTripFromLeg(EditTrips.java:102)
	at org.matsim.withinday.utils.EditTrips.replanCurrentTrip(EditTrips.java:92)
	at org.matsim.withinday.utils.EditPlans.addActivityAtEnd(EditPlans.java:53)
	at io.github.agentsoz.bdimatsim.DRIVETODefaultActionHandler.handle(DRIVETODefaultActionHandler.java:106)
	at io.github.agentsoz.nonmatsim.ActionHandler.processAction(ActionHandler.java:75)
	at io.github.agentsoz.nonmatsim.PAAgentManager.initiateNewAction(PAAgentManager.java:139)
	at io.github.agentsoz.nonmatsim.PAAgentManager.updateActions(PAAgentManager.java:112)
	at io.github.agentsoz.bdimatsim.MATSimModel.runUntil(MATSimModel.java:357)
	at io.github.agentsoz.ees.Main.start(Main.java:176)
	at io.github.agentsoz.ees.Main.main(Main.java:461)
	at io.github.agentsoz.ees.BlockageTorquay500Test.testTorquay500(BlockageTorquay500Test.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatchman$1.evaluate(TestWatchman.java:53)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.711 s <<< FAILURE! - in io.github.agentsoz.ees.BlockageTorquay500Test
[ERROR] testTorquay500(io.github.agentsoz.ees.BlockageTorquay500Test)  Time elapsed: 17.481 s  <<< ERROR!
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at io.github.agentsoz.ees.BlockageTorquay500Test.testTorquay500(BlockageTorquay500Test.java:48)
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at io.github.agentsoz.ees.BlockageTorquay500Test.testTorquay500(BlockageTorquay500Test.java:48)
```

**Comment by dhixsingh** [comment]
@osbornejr, I've just restarted Travis build 495 again, to see if the error is reproduced.

**Comment by osbornejr** [comment]
There could be an issue on my end with matsim version? I am on matsim kaibranch, which still builds 0.10.0 SNAPSHOT. The master is 0.11.0 SNAPSHOT.

EDIT: kaibranch is actually 0.11.0 SNAPSHOT. I will have to build the repo properly again I think.

**Comment by dhixsingh** [comment]
Why are your versions different? Are you not using the same POM+travis set up throughout? You should be. `kaibranch` actually uses 0.10.0 release btw:

https://github.com/agentsoz/bdi-abm-integration/blob/1734411ac790f5430c494fce305eeef77cafb760/integrations/bdi-matsim/pom.xml#L35-L39.

The re-run of the build failed. I guess it is to do with your versions then.

**Comment by dhixsingh** [comment]
And travis no longer requires a checkout of MATSim:
https://github.com/agentsoz/bdi-abm-integration/blob/1734411ac790f5430c494fce305eeef77cafb760/.travis.yml#L7-L12

**Comment by dhixsingh** [comment]
@osbornejr  also `examples/bushfire/scenarios/otways/otways-300/matsim_output` should not be checked in. Any expected results files should be only in  `examples/bushfire/test/input/...`

**Comment by osbornejr** [comment]
Sorry, I meant the matsim/kaibranch is at 0.11.0 SNAPSHOT. But yes as you say, that shouldn't matter, because it is now using the .10.0 release. 

Yes, my travis file is the same as the one above. I think version wise I am fine, just got confused because I hadn't rebuilt matsim since before the latest release.

I have removed the /matsim_output, not sure why that was there.

**Comment by osbornejr** [comment]
Ok now merging the latest kaibranch commit has caused failure locally and on travis, so I'll work out what has changed now. Still weird because the merge seemed to just add the Denmark scenario directory.

**Comment by osbornejr** [comment]
@dhixsingh Should I/you go ahead and merge this?

**Comment by dhixsingh** [comment]
Yes I will do that.

**Pull request merged**
